new

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -80,7 +80,14 @@ jobs:
             ce_task_id=$(cat $REPORT_PATH | grep $CE_TASK_ID_KEY | cut -d'=' -f2)
             echo "Using task id of ${ce_task_id}"
             ce_analysis_id=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=$ce_task_id | jq -r .task.analysisId)
-
+            echo "Using analysis id of ${ce_analysis_id}"
+            # get the status of the quality gate for this analysisId
+            qg_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/qualitygates/project_status?analysisId="${ce_analysis_id}" | jq -r .projectStatus.status)
+            echo "Quality Gate status is ${qg_status}"
+            if [ "${qg_status}" != "OK" ]; then
+              echo "Quality gate is not OK - exiting with error"
+              exit 1
+            fi
 
 workflows:
   build_and_test:
